[package]
name = "index-pgn"
version = "0.0.0"
publish = false

[dependencies]
pgn-reader = { path = "/home/niklas/Projekte/rust-pgn-reader" }
memmap = "0.6"
madvise = "0.1"
btoi = "0.1"
rand = "0.3"
